# Generated by Django 4.1.7 on 2023-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('url', models.URLField()),
                ('data', models.DateTimeField()),
            ],
        ),
    ]
