# Generated by Django 4.1.7 on 2023-03-17 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nius', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'Newsy'},
        ),
    ]
