# Generated by Django 4.1.7 on 2023-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nius', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.URLField(default='https://trzydoliny.eu'),
            preserve_default=False,
        ),
    ]
