# Generated by Django 4.1.7 on 2023-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nius', '0003_news_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
