# Generated by Django 4.1.7 on 2023-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nius', '0004_news_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
