# Generated by Django 4.1.7 on 2023-03-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nius', '0006_alter_news_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
