zrodla = {
    'https://trzydoliny.eu' : 'LGD',
    'https://www.gov.pl/web/cppc/lista-aktualnosci': 'CCCP',
    'https://www.gov.pl/web/uw-kujawsko-pomorski/wiadomosci2':'Urząd Wojewódzki', 
    'https://www.gov.pl/web/fundusze-regiony/aktualnosci1':'Ministerstwo Funduszy',
    'https://www.gov.pl/web/sport/wiadomosci':'Ministerstwo Sportu',
    'https://www.gov.pl/web/premier/wydarzenia':'Premier',
    'https://www.gov.pl/web/infrastruktura/aktualnosci':'Ministerstwo Infrastruktury',
    'https://www.gov.pl/web/edukacja-i-nauka/wiadomosci':'Ministerstwo Edukacji',
    'https://www.gov.pl/web/sport/dofinansowanie-zadan-z-funduszu-rozwoju-kultury-fizycznej-201948':'Fundusz Rozwoju Kultury Fizycznej',
    'https://www.funduszeeuropejskie.gov.pl/strony/wiadomosci#/najnowsze=1':'Fundusze Europejskie',
    'https://www.funduszeeuropejskie.gov.pl/strony/o-funduszach/fundusze-2021-2027/aktualnosci/#/domyslne=1':'Fundusze Europejskie -  Aktualności',
    'https://www.polskacyfrowa.gov.pl/strony/o-programie/fundusze-europejskie-na-rozwoj-cyfrowy-2021-2027/aktualnosci/#/domyslne=1':'Fundusze na rozwój cyfrowy',
    'https://www.poir.gov.pl/strony/o-programie/fe-dla-nowoczesnej-gospodarki/aktualnosci/#/domyslne=1':'Nowoczesna Gospodarka',
    'https://www.rozwojspoleczny.gov.pl/strony/aktualnosci#/domyslne=1':'Rozwoj Społeczny', 
    'https://www.rozwojcyfrowy.gov.pl/strony/aktualnosci/#/domyslne=1':'Fundusze na rozwój cyfrowy aktualności', 
    'https://www.nowoczesnagospodarka.gov.pl/strony/aktualnosci/#/domyslne=1':'Nowoczesna Gospodarka Aktualności', 
    'https://www.feniks.gov.pl/strony/aktualnosci/#/domyslne=1':'Feniks',
    'https://mojregion.eu/rpo/wiadomosci/':'Mojregion',
    'https://mojregion.eu/prow/aktualnosci/':'PROW',
    'https://efrwp.pl/':'EFRPW',
    'https://portal-sow.pfron.org.pl/opencms/export/sites/pfron-sow/sow/aktualnosci/':'SOW',
    'https://bip.kujawsko-pomorskie.pl/':'BIP K-P'}